/*CREATE TABLE GklsPasPaleGreatWorkCommon(
    GreatWorkType TEXT NOT NULL,
    GreatWorkObjectType TEXT NOT NULL,
    GreatPersonIndividualType TEXT NOT NULL
);

CREATE TABLE GklsPasPaleGreatWorkSP(
    GreatWorkType TEXT NOT NULL,
    GreatWorkObjectType TEXT NOT NULL,
    GreatPersonIndividualType TEXT NOT NULL
);

INSERT INTO GklsPasPaleGreatWorkCommon
(GreatWorkType,  GreatWorkObjectType, GreatPersonIndividualType)
VALUES
('GREATWORK_SAYURI_gkls621', 'GREATWORKOBJECT_PORTRAIT', 'GREAT_PERSON_INDIVIDUAL_SAYURI_gkls621_SHADOW'),

('GREATWORK_PLADY_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_PLADY_gkls621_SHADOW'),

('GREATWORK_MOMOE_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_MOMOE_gkls621_SHADOW'),

('GREATWORK_SEIKO_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_SEIKO_gkls621_SHADOW'),

('GREATWORK_MARI_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_MARI_gkls621_SHADOW'),

('GREATWORK_AKINA_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_AKINA_gkls621_SHADOW'),

('GREATWORK_NORIKO_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_NORIKO_gkls621_SHADOW'),

('GREATWORK_YUKIKO_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_YUKIKO_gkls621_SHADOW'),

('GREATWORK_MEGUMI_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_MEGUMI_gkls621_SHADOW'),

('GREATWORK_SPEED_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_SPEED_gkls621_SHADOW'),

('GREATWORK_MORNING_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_MORNING_gkls621_SHADOW'),

('GREATWORK_AKB48_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_AKB48_gkls621_SHADOW'),

('GREATWORK_CLOVERZ_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_CLOVERZ_gkls621_SHADOW'),

('GREATWORK_765AS_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_765AS_gkls621_SHADOW'),

('GREATWORK_MUS_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_MUS_gkls621_SHADOW'),

('GREATWORK_PASPALE_gkls621', 'GREATWORKOBJECT_MUSIC', 'GREAT_PERSON_INDIVIDUAL_PASPALE_gkls621_SHADOW');

INSERT INTO GklsPasPaleGreatWorkSP
(GreatWorkType,  GreatWorkObjectType, GreatPersonIndividualType)
VALUES
('GREATWORK_PLADY_SP_gkls621', 'GREATWORKOBJECT_WRITING',    'GREAT_PERSON_INDIVIDUAL_PLADY_gkls621_SHADOW'),

('GREATWORK_MOMOE_SP_gkls621', 'GREATWORKOBJECT_LANDSCAPE', 'GREAT_PERSON_INDIVIDUAL_MOMOE_gkls621_SHADOW'),

('GREATWORK_SEIKO_SP_gkls621', 'GREATWORKOBJECT_WRITING',    'GREAT_PERSON_INDIVIDUAL_SEIKO_gkls621_SHADOW'),

('GREATWORK_MARI_SP_gkls621', 'GREATWORKOBJECT_PORTRAIT', 'GREAT_PERSON_INDIVIDUAL_MARI_gkls621_SHADOW'),

('GREATWORK_AKINA_SP_gkls621', 'GREATWORKOBJECT_WRITING',    'GREAT_PERSON_INDIVIDUAL_AKINA_gkls621_SHADOW'),

('GREATWORK_NORIKO_SP_gkls621', 'GREATWORKOBJECT_WRITING',   'GREAT_PERSON_INDIVIDUAL_NORIKO_gkls621_SHADOW'),

('GREATWORK_MEGUMI_SP_gkls621', 'GREATWORKOBJECT_PORTRAIT',    'GREAT_PERSON_INDIVIDUAL_MEGUMI_gkls621_SHADOW'),

('GREATWORK_SPEED_SP_gkls621', 'GREATWORKOBJECT_WRITING',    'GREAT_PERSON_INDIVIDUAL_SPEED_gkls621_SHADOW'),

('GREATWORK_MORNING_SP_gkls621', 'GREATWORKOBJECT_WRITING',  'GREAT_PERSON_INDIVIDUAL_MORNING_gkls621_SHADOW'),

('GREATWORK_AKB48_SP_gkls621', 'GREATWORKOBJECT_WRITING',    'GREAT_PERSON_INDIVIDUAL_AKB48_gkls621_SHADOW'),

('GREATWORK_CLOVERZ_SP_gkls621', 'GREATWORKOBJECT_WRITING',  'GREAT_PERSON_INDIVIDUAL_CLOVERZ_gkls621_SHADOW'),

('GREATWORK_765AS_SP_gkls621', 'GREATWORKOBJECT_PORTRAIT',  'GREAT_PERSON_INDIVIDUAL_765AS_gkls621_SHADOW'),

('GREATWORK_MUS_SP_gkls621', 'GREATWORKOBJECT_PORTRAIT',    'GREAT_PERSON_INDIVIDUAL_MUS_gkls621_SHADOW'),

('GREATWORK_PASPALE_SP_gkls621', 'GREATWORKOBJECT_PORTRAIT',    'GREAT_PERSON_INDIVIDUAL_PASPALE_gkls621_SHADOW');

INSERT INTO Types
(Type,  Kind)
SELECT
GreatWorkType, 'KIND_GREATWORK'
FROM GklsPasPaleGreatWorkCommon;

INSERT INTO Types
(Type,  Kind)
SELECT
GreatWorkType, 'KIND_GREATWORK'
FROM GklsPasPaleGreatWorkSP;

INSERT INTO GreatWorks
(GreatWorkType,
GreatWorkObjectType,
GreatPersonIndividualType,
Name,
Tourism
)
SELECT
GreatWorkType,
GreatWorkObjectType,
GreatPersonIndividualType,
'LOC_' || GreatWorkType || '_NAME',
4
FROM GklsPasPaleGreatWorkCommon;

INSERT INTO GreatWorks
(GreatWorkType,
GreatWorkObjectType,
GreatPersonIndividualType,
Name,
Tourism
)
SELECT
GreatWorkType,
GreatWorkObjectType,
GreatPersonIndividualType,
'LOC_' || GreatWorkType || '_NAME',
4
FROM GklsPasPaleGreatWorkSP;

INSERT INTO GreatWork_YieldChanges
(GreatWorkType, YieldType,  YieldChange)
SELECT
GreatWorkType, 'YIELD_CULTURE', 3
FROM GklsPasPaleGreatWorkCommon;

INSERT INTO GreatWork_YieldChanges
(GreatWorkType, YieldType,  YieldChange)
SELECT
GreatWorkType, 'YIELD_CULTURE', 4
FROM GklsPasPaleGreatWorkSP; */